core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStore.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStore.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreTemplate.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordRepositoryConnectorFactory.java
Template config is OPTIONAL, and global values are used if not present. Store config is MANDATORY, and reflects the values used at its creation.
Fixes #8
=> Issue 8 addendum

plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/RedeployMojo.java
And keep "merge" mojo (as defunct) for now.
Fixes #13
=> Rename existing mojo "merge" to "redeploy"

core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStore.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreTemplate.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordRepositoryConnectorFactory.java, it/extension-its/src/it/basic/invoker.properties, it/extension-its/src/it/basic/verify.groovy
By making it default.
Fixes #15
=> Encourage use of SHA-512

core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreManager.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordRepositoryConnectorFactory.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ListTemplatesMojo.java
Add new mojo to let user list available templates.
=> Add mojo to list templates

core/pom.xml, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/publisher/ArtifactStorePublisherSupport.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStore.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultArtifactStoreExporter.java, core/src/main/java/eu/maveniverse/maven/njord/shared/publisher/ArtifactStorePublisher.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreExporter.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordRepositoryConnector.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportBundleMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/PublishMojo.java, publisher/apache/pom.xml, publisher/apache/src/main/java/eu/maveniverse/maven/njord/publisher/apache/ApacheRaoPublisherFactory.java, publisher/sonatype/pom.xml, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisherFactory.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeNx2Publisher.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeS01PublisherFactory.java
=> Central publishing

core/src/main/java/eu/maveniverse/maven/njord/shared/impl/repository/DefaultInternalArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreTemplate.java, it/extension-its/src/it/merge-all-release/.mvn/extensions.xml, it/extension-its/src/it/merge-all-release/README.md, it/extension-its/src/it/merge-all-release/invoker.properties, it/extension-its/src/it/merge-all-release/pom.xml, it/extension-its/src/it/merge-all-release/verify.groovy, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/DropAllMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/DropMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ImportAllMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ImportMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ListContentMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/MergeAllMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/MergeMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/PublishMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/RedeployMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ValidateMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/WriteBundleMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/WriteMojo.java
These are just simple mojos to help automation.
=> MergeAll and ImportAll mojos

core/src/main/java/eu/maveniverse/maven/njord/shared/NjordSession.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/DefaultNjordSession.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/DefaultNjordSessionFactory.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/comparator/ArtifactStoreComparatorSupport.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/comparator/BitwiseArtifactStoreComparator.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/comparator/BitwiseArtifactStoreComparatorFactory.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/comparator/ComparisonContext.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/publisher/DefaultArtifactStoreValidator.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/ArtifactStoreDeployer.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStore.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStoreMerger.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStoreMergerFactory.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStoreWriter.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStoreWriterFactory.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultInternalArtifactStoreManager.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultInternalArtifactStoreManagerFactory.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreComparator.java, core/src/main/java/eu/maveniverse/maven/njord/shared/store/ArtifactStoreComparatorFactory.java, it/extension-its/src/it/compare/.mvn/extensions.xml, it/extension-its/src/it/compare/README.md, it/extension-its/src/it/compare/invoker.properties, it/extension-its/src/it/compare/pom.xml, it/extension-its/src/it/compare/verify.groovy, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/CompareMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ListComparatorsMojo.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeNx2Publisher.java
Introduce comparator and new mojos to compare stores. Added IT, that will fail if build is not reproducible.
Fixes #37
=> Compare stores

core/src/main/java/eu/maveniverse/maven/njord/shared/SessionConfig.java
Which it was, but move all def methods to ctor as well.
Fixes #44
=> Immutable session config

extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/StatusMojo.java
It should be TLP and not first project built.
Fixes #62
=> Fix prefix

core/src/main/java/eu/maveniverse/maven/njord/shared/impl/DefaultSession.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/PublisherSupportMojo.java
If autoPublish is enabled, but there is nothing to publish Njord should not fail.
Fixes #76
=> Bug: autoPublish eagerly wants publisher

plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/NjordMojoSupport.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/StatusMojo.java
Right now, only status mojo works with temp
session. But in general, all the mojos should
be workable from whenever they are invoked.
=> Make Mojos work with temp session if needed

pom.xml
There was a bug when DirectoryLocker "lost": https://github.com/maveniverse/maven-shared/releases/tag/release-0.1.5
=> Update maven-shared to 0.1.5

core/src/main/java/eu/maveniverse/maven/njord/shared/NjordUtils.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java
=> Simplify init

core/pom.xml, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java, publisher/apache/pom.xml, publisher/deploy/pom.xml, publisher/sonatype/pom.xml
By "blurring" all the deps scopes across all, as currently there is no better (and simpler) way.
Also, fix obscure logging when unsupported Maven version use attempted.
Fixes #100
=> Fix Njord CP

publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisherConfig.java
Support the "automatic" mode.
Fixes #66
=> SCP config bug fixes and improvement

core/src/main/java/eu/maveniverse/maven/njord/shared/Session.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/DefaultSession.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java
The build did not fail when autoPublishing without auth but should. To simplify, removed for now "derived" session and just streamlined all.
=> Fix Deploy w/o auth

plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportAllMojo.java
=> New mojo: export-all

core/src/main/java/eu/maveniverse/maven/njord/shared/SessionConfig.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultArtifactStoreWriter.java, core/src/main/java/eu/maveniverse/maven/njord/shared/impl/store/DefaultInternalArtifactStoreManager.java, extension/src/main/filtered-resources/runtime-requirements.properties, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordRepositoryConnectorFactory.java, extension/src/main/java/eu/maveniverse/maven/njord/extension3/NjordSessionLifecycleParticipant.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportAllMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ExportMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ImportAllMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/ImportMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/NjordMojoSupport.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/WriteBundleMojo.java, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/WriteMojo.java, pom.xml
Revamp config, that as a side effect has ability to work in older Maven versions IF Njord is disabled.
=> Rework config

plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/CheckArtifactsAvailabilityMojo.java
Publishing will not happen "immediately", there is no reason to start polling target as soon as mojo is invoked, but add possibility to have a delay before the first check.
This delay is NOT included into waitTimeout, hence the "worst case" of this mojo runtime is `waitDelay + waitTimeout`.
=> Add waitDelay parameter to check-artifacts-availability mojo

it/extension-its/pom.xml, it/extension-its/src/it/check-artifacts-availability-manual-pom/.mvn/extensions.xml, it/extension-its/src/it/check-artifacts-availability-manual-pom/README.md, it/extension-its/src/it/check-artifacts-availability-manual-pom/invoker.properties, it/extension-its/src/it/check-artifacts-availability-manual-pom/list.txt, it/extension-its/src/it/check-artifacts-availability-manual-pom/pom.xml, plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/CheckArtifactsAvailabilityMojo.java
That is the loaded up. File should contain artifact strings in expected format, each on new line.
=> Make artifacts parameter possible to point at a file

publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java
=> Add proxy support

core/src/main/java/eu/maveniverse/maven/njord/shared/SessionConfig.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java
Changes:
* if project present, create upload bundle under /target
* log what we uploaded
Fixes #144
Fixes #145
=> Smaller fixes

publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisher.java, publisher/sonatype/src/main/java/eu/maveniverse/maven/njord/publisher/sonatype/SonatypeCentralPortalPublisherConfig.java
=> Add log at end of publishing where to continue

plugin/src/main/java/eu/maveniverse/maven/njord/plugin3/NjordMojoSupport.java
When extension and plugin versions are not aligned (possible when extesion is loaded), warn the user as it may cause problems.
Best practice is to keep the two aligned.
=> Mojo warns on misaligned versions
